---
language: csharp

dist: trusty
sudo: required

dotnet: 2.0.0

mono:
 - 4.8.0
 - 5.2.0
 - latest # => "stable release"
 - weekly # => "latest commits"

install:
 - rvm install 2.2.3
 - gem install bundler
 - sudo apt-get update -y
 - sudo apt-get install -y gnupg automake libtool
 - curl -sSL https://github.com/libuv/libuv/archive/v1.9.1.tar.gz | tar zxf - -C /tmp
 - (cd /tmp/libuv-1.9.1/ && ./autogen.sh && ./configure && make && sudo make install)
 - sudo ldconfig
 # for apache bench (ab)
 - sudo apt-get install -qq apache2-utils

script:
 - bundle && bundle exec rake ci

matrix:
  allow_failures:
    - mono: latest
    - mono: weekly
    - mono: 5.0.0
