version: 1.0.{build}

environment:
  matrix:
   - arch: "x86"
     MSBUILD_PLATFORM: x86
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"

install:
 - ps: Start-FileDownload 'https://github.com/libuv/libuv/archive/v1.9.1.zip'
 - cmd: 7z x v1.9.1.zip & cd libuv-1.9.1 & vcbuild.bat %arch% shared debug
 - cmd: mkdir src\Suave.Tests\bin\Release\ & cp libuv-1.9.1\Debug\libuv.dll src\Suave.Tests\bin\Release\libuv.dll
 
build_script:
 - cmd: gem sources -r https://rubygems.org/
 - cmd: gem install bundler --no-ri --no-rdoc --source http://rubygems.org/
 - cmd: bundle install
 - cmd: bundle exec rake appveyor
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true


