version: 3.0.0-alpha.{build}

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
- cmd: build.cmd

init:
  - git config --global core.autocrlf input

environment:
  matrix:
   - arch: "x86"
     MSBUILD_PLATFORM: x86
     PATH: '%USERPROFILE%\.nuget\packages\libuv\1.10.0\runtimes\win-x86\native;%PATH%'
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"
     PATH: '%USERPROFILE%\.nuget\packages\libuv\1.10.0\runtimes\win-x64\native;%PATH%'
 
artifacts:
 - path: build\pkg\*.nupkg 

test: off

nuget:
  project_feed: true